"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import {
  Download, ChevronLeft, FileText, Hash, Search, Tag,
  Wand2, Pin, Users, Scissors, Type,
  CheckCircle, Copy, Check, Sparkles
} from "lucide-react";
import { useVideoEngineStore } from "@/lib/video-engine/state";
import { WizardProgress } from "@/components/video-engine/WizardProgress";

// ─── Text builders ────────────────────────────────────────────────────────

function flattenKit(videoKit: any): string {
  const lines: string[] = [];
  lines.push("=".repeat(52));
  lines.push("        YT LAUNCHPAD — VIDEO KIT EXPORT");
  lines.push("=".repeat(52));
  lines.push("");

  if (videoKit?.thumbnail_brief) {
    const t = videoKit.thumbnail_brief;
    lines.push("THUMBNAIL BRIEF");
    lines.push("-".repeat(30));
    lines.push(`Headline   : ${t.headline}`);
    lines.push(`Emotion    : ${t.emotion}`);
    lines.push(`Composition: ${t.composition}`);
    if (t.color_suggestions?.length) lines.push(`Colors     : ${t.color_suggestions.join(", ")}`);
    if (t.prompt) { lines.push(""); lines.push(`Visual Prompt:\n${t.prompt}`); }
    lines.push("");
  }

  if (videoKit?.titles?.length) {
    lines.push("TITLES");
    lines.push("-".repeat(30));
    videoKit.titles.forEach((t: any, i: number) => {
      lines.push(`${i + 1}. ${t.title}  [CTR: ${t.ctr_score} | SEO: ${t.seo_score}]`);
    });
    lines.push("");
  }

  if (videoKit?.description) {
    const d = videoKit.description;
    lines.push("DESCRIPTION");
    lines.push("-".repeat(30));
    lines.push(d.description ?? "");
    if (d.cta) { lines.push(""); lines.push(`CTA: ${d.cta}`); }
    if (d.links_placeholder) { lines.push(""); lines.push(`Links:\n${d.links_placeholder}`); }
    if (d.chapters?.length) { lines.push(""); lines.push("Chapters:"); d.chapters.forEach((c: string) => lines.push(`  ${c}`)); }
    lines.push("");
  }

  if (videoKit?.hashtags) {
    const h = videoKit.hashtags;
    lines.push("HASHTAGS");
    lines.push("-".repeat(30));
    if (h.primary?.length) lines.push(`Primary   : ${h.primary.join(" ")}`);
    if (h.secondary?.length) lines.push(`Secondary : ${h.secondary.join(" ")}`);
    if (h.trending?.length) lines.push(`Trending  : ${h.trending.join(" ")}`);
    lines.push("");
  }

  if (videoKit?.keywords) {
    const k = videoKit.keywords;
    lines.push("KEYWORDS");
    lines.push("-".repeat(30));
    if (k.primary?.length) lines.push(`Primary   : ${k.primary.join(", ")}`);
    if (k.secondary?.length) lines.push(`Secondary : ${k.secondary.join(", ")}`);
    if (k.long_tail?.length) lines.push(`Long tail : ${k.long_tail.join(", ")}`);
    lines.push("");
  }

  if (videoKit?.tags?.length) {
    lines.push("YOUTUBE TAGS");
    lines.push("-".repeat(30));
    lines.push(videoKit.tags.join(", "));
    lines.push("");
  }

  if (videoKit?.thumbnail_prompt) {
    const tp = videoKit.thumbnail_prompt;
    lines.push("AI IMAGE PROMPT");
    lines.push("-".repeat(30));
    lines.push(tp.image_prompt ?? String(tp));
    if (tp.style_notes) { lines.push(""); lines.push(`Style Notes: ${tp.style_notes}`); }
    lines.push("");
  }

  if (videoKit?.pinned_comment) {
    lines.push("PINNED COMMENT");
    lines.push("-".repeat(30));
    lines.push(videoKit.pinned_comment);
    lines.push("");
  }

  if (videoKit?.community_post) {
    lines.push("COMMUNITY POST");
    lines.push("-".repeat(30));
    lines.push(videoKit.community_post);
    lines.push("");
  }

  if (videoKit?.shorts_caption) {
    lines.push("SHORTS CAPTION");
    lines.push("-".repeat(30));
    lines.push(videoKit.shorts_caption);
    lines.push("");
  }

  if (videoKit?.social_kit) {
    const s = videoKit.social_kit;
    lines.push("SOCIAL PROMO KIT");
    lines.push("-".repeat(30));
    if (s.twitter) lines.push(`X / Twitter:\n${s.twitter}\n`);
    if (s.facebook) lines.push(`Facebook:\n${s.facebook}\n`);
    if (s.instagram) lines.push(`Instagram:\n${s.instagram}\n`);
    if (s.linkedin) lines.push(`LinkedIn:\n${s.linkedin}\n`);
  }

  lines.push("=".repeat(52));
  lines.push("Generated by YT Launchpad");
  lines.push("=".repeat(52));
  return lines.join("\n");
}

function flattenScript(script: any): string {
  if (!script) return "";
  const lines: string[] = [];
  lines.push("=".repeat(52));
  lines.push("        YT LAUNCHPAD — SCRIPT EXPORT");
  lines.push("=".repeat(52));
  lines.push("");
  const sections = ["intro", "hook_segment", "body", "conclusion", "cta"];
  sections.forEach((sec) => {
    const s = script[sec];
    if (!s) return;
    lines.push(`[${s.title?.toUpperCase() ?? sec.toUpperCase()}]`);
    lines.push("-".repeat(40));
    if (s.content) lines.push(s.content);
    if (s.b_roll_suggestion) lines.push(`\n[B-Roll: ${s.b_roll_suggestion}]`);
    if (s.visual_cue) lines.push(`[Visual: ${s.visual_cue}]`);
    lines.push("");
  });
  lines.push("=".repeat(52));
  return lines.join("\n");
}

// ─── Copy Button ──────────────────────────────────────────────────────────

function CopyBtn({ text, label = "Copy" }: { text: string; label?: string }) {
  const [copied, setCopied] = useState(false);
  return (
    <button
      onClick={() => { navigator.clipboard.writeText(text); setCopied(true); setTimeout(() => setCopied(false), 1800); }}
      className={`flex items-center gap-1.5 text-xs font-medium px-3 py-1.5 rounded-lg border transition-all duration-150 ${
        copied
          ? "bg-green-50 border-green-200 text-green-700"
          : "bg-gray-50 border-gray-200 text-gray-500 hover:bg-gray-100"
      }`}
    >
      {copied ? <Check className="w-3.5 h-3.5" /> : <Copy className="w-3.5 h-3.5" />}
      {copied ? "Copied!" : label}
    </button>
  );
}

// ─── Export Card ──────────────────────────────────────────────────────────

function ExportCard({
  icon: Icon,
  iconBg,
  iconColor,
  title,
  subtitle,
  text,
  onDownload,
}: {
  icon: any;
  iconBg: string;
  iconColor: string;
  title: string;
  subtitle: string;
  text: string;
  onDownload: () => void;
}) {
  return (
    <div className="bg-white rounded-2xl border border-gray-200 overflow-hidden shadow-sm hover:shadow-md transition-shadow duration-200">
      <div className="flex items-center justify-between px-5 py-4 border-b border-gray-100">
        <div className="flex items-center gap-3">
          <div className="w-9 h-9 rounded-xl flex items-center justify-center" style={{ background: iconBg }}>
            <Icon className="w-4 h-4" style={{ color: iconColor }} />
          </div>
          <div>
            <p className="font-bold text-sm text-gray-900">{title}</p>
            <p className="text-xs text-gray-400 mt-0.5">{subtitle}</p>
          </div>
        </div>
        <div className="flex items-center gap-2">
          <span className="text-xs text-gray-400 hidden sm:block">{text.split("\n").length} lines</span>
          <CopyBtn text={text} />
          <button
            onClick={onDownload}
            className="flex items-center gap-1.5 text-xs font-semibold px-3 py-1.5 rounded-lg bg-blue-600 hover:bg-blue-700 text-white transition-colors duration-150"
          >
            <Download className="w-3.5 h-3.5" />
            .txt
          </button>
        </div>
      </div>
      <div className="px-5 py-4">
        <pre className="text-xs text-gray-500 whitespace-pre-wrap leading-relaxed max-h-48 overflow-auto font-mono">
          {text.slice(0, 600)}{text.length > 600 ? "\n…" : ""}
        </pre>
      </div>
    </div>
  );
}

// ─── Page ─────────────────────────────────────────────────────────────────

export default function ExportPage() {
  const router = useRouter();
  const { videoKit, script, selectedTopic, getContentContext } = useVideoEngineStore();
  const [hydrated, setHydrated] = useState(false);

  useEffect(() => {
    const check = () => {
      const ctx = getContentContext();
      if (!ctx) { router.replace("/video-engine"); return; }
      setHydrated(true);
    };
    if (useVideoEngineStore.persist.hasHydrated()) check();
    else {
      const unsub = useVideoEngineStore.persist.onFinishHydration(() => check());
      return () => unsub();
    }
  }, []);

  if (!hydrated) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center">
        <div className="w-6 h-6 border-2 border-blue-500 border-t-transparent rounded-full animate-spin" />
      </div>
    );
  }

  const kitText = flattenKit(videoKit);
  const scriptText = script ? flattenScript(script) : "";
  const allText = [scriptText, kitText].filter(Boolean).join("\n\n");

  const topicLabel = selectedTopic?.topic ?? "video";
  const safeLabel = topicLabel.replace(/[^a-z0-9]/gi, "_").toLowerCase().slice(0, 40);

  function download(content: string, name: string) {
    const blob = new Blob([content], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = name;
    a.click();
    URL.revokeObjectURL(url);
  }

  const hasKit = Object.keys(videoKit).length > 0;
  const hasScript = !!script;

  return (
    <div className="min-h-screen bg-gray-50">
      <WizardProgress currentStep={8} />

      <div className="max-w-4xl mx-auto px-4 py-8">
        {/* Header */}
        <div className="mb-8">
          <div className="flex items-center gap-2 mb-3">
            <span className="text-xs font-semibold text-blue-600 uppercase tracking-wider">Final Step</span>
            <span className="text-xs text-gray-300">·</span>
            <span className="text-xs text-gray-400">Download your content as .txt files</span>
          </div>
          <div className="flex items-start justify-between gap-4 flex-wrap">
            <div>
              <h1 className="text-2xl font-black text-gray-900 flex items-center gap-2">
                <Sparkles className="w-6 h-6 text-blue-500" />
                Export Your Content
              </h1>
              <p className="text-gray-500 text-sm mt-1">Download your script and video kit, or copy individual sections.</p>
            </div>
            {(hasKit || hasScript) && (
              <button
                onClick={() => download(allText, `ytlaunchpad_${safeLabel}_full.txt`)}
                className="flex-shrink-0 flex items-center gap-2 px-5 py-2.5 bg-gradient-to-r from-blue-600 to-indigo-600 hover:from-blue-700 hover:to-indigo-700 text-white text-sm font-bold rounded-xl shadow-md hover:shadow-lg transition-all duration-200"
              >
                <Download className="w-4 h-4" />
                Download All
              </button>
            )}
          </div>
        </div>

        {/* Warning if nothing generated */}
        {!hasKit && !hasScript && (
          <div className="mb-6 p-4 bg-amber-50 border border-amber-200 rounded-xl flex items-center gap-3">
            <span className="text-amber-500 text-lg">⚠️</span>
            <p className="text-sm text-amber-700 font-medium">
              No content generated yet. Please go back and complete the kit generation first.
            </p>
          </div>
        )}

        {/* Export cards */}
        <div className="space-y-4">
          {hasScript && (
            <ExportCard
              icon={FileText}
              iconBg="#eff6ff"
              iconColor="#3b82f6"
              title="Video Script"
              subtitle="Full script with intro, hook, body, conclusion & CTA"
              text={scriptText}
              onDownload={() => download(scriptText, `ytlaunchpad_${safeLabel}_script.txt`)}
            />
          )}
          {hasKit && (
            <ExportCard
              icon={Sparkles}
              iconBg="#f5f3ff"
              iconColor="#7c3aed"
              title="Complete Video Kit"
              subtitle="Titles, description, hashtags, tags, social kit & more"
              text={kitText}
              onDownload={() => download(kitText, `ytlaunchpad_${safeLabel}_kit.txt`)}
            />
          )}
        </div>

        {/* Quick copy individual sections */}
        {hasKit && (
          <div className="mt-6 bg-white rounded-2xl border border-gray-200 overflow-hidden shadow-sm">
            <div className="px-5 py-3.5 border-b border-gray-100">
              <p className="font-bold text-sm text-gray-900">Quick Copy — Individual Sections</p>
              <p className="text-xs text-gray-400 mt-0.5">Copy any single section directly to clipboard</p>
            </div>
            <div className="grid grid-cols-2 sm:grid-cols-3 divide-x divide-y divide-gray-100">
              {[
                { key: "titles",           label: "Titles",          icon: Type,     color: "#3b82f6" },
                { key: "description",      label: "Description",     icon: FileText,  color: "#10b981" },
                { key: "hashtags",         label: "Hashtags",        icon: Hash,      color: "#ec4899" },
                { key: "keywords",         label: "Keywords",        icon: Search,    color: "#f97316" },
                { key: "tags",             label: "YT Tags",         icon: Tag,       color: "#14b8a6" },
                { key: "thumbnail_prompt", label: "AI Prompt",       icon: Wand2,     color: "#7c3aed" },
                { key: "pinned_comment",   label: "Pinned Comment",  icon: Pin,       color: "#ef4444" },
                { key: "community_post",   label: "Community Post",  icon: Users,     color: "#6366f1" },
                { key: "shorts_caption",   label: "Shorts Caption",  icon: Scissors,  color: "#f59e0b" },
              ].map(({ key, label, icon: Icon, color }) => {
                const raw = (videoKit as any)[key];
                if (!raw) return null;
                const copyText = typeof raw === "string"
                  ? raw
                  : Array.isArray(raw)
                  ? raw.map((t: any) => t.title ?? String(t)).join("\n")
                  : JSON.stringify(raw, null, 2);
                return (
                  <div key={key} className="px-4 py-3 flex items-center justify-between gap-2 hover:bg-gray-50">
                    <div className="flex items-center gap-2 min-w-0">
                      <Icon className="w-3.5 h-3.5 flex-shrink-0" style={{ color }} />
                      <span className="text-xs font-medium text-gray-700 truncate">{label}</span>
                    </div>
                    <CopyBtn text={copyText} />
                  </div>
                );
              })}
            </div>
          </div>
        )}

        {/* Bottom nav */}
        <div className="mt-8 flex justify-between items-center">
          <button
            onClick={() => router.back()}
            className="flex items-center gap-2 text-gray-500 hover:text-gray-700 text-sm font-medium transition-colors"
          >
            <ChevronLeft className="w-4 h-4" /> Back to Kit
          </button>
          <div className="flex items-center gap-2 text-xs text-gray-400">
            <CheckCircle className="w-4 h-4 text-green-500" />
            All done! Your video is ready to publish.
          </div>
        </div>
      </div>
    </div>
  );
}
